#!/usr/bin/env bash
set -e

echo '[git pre-commit] mvn spotless:apply sortpom:sort'
MAVEN_OPTS='-Dorg.slf4j.simpleLogger.defaultLogLevel=error' mvn spotless:apply sortpom:sort

staged_files=$(git diff --name-only --cached)
for file in $staged_files; do
    git add "$file"
done
