name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MAVEN_ARGS: --batch-mode --no-transfer-progress -V -e -Dstyle.color=always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Get hyperd version
        id: evaluate-property
        run: |
          HYPER_VERSION=$(grep "<hyperapi.version>" pom.xml | sed -n 's/.*<hyperapi.version>\(.*\)<\/hyperapi.version>.*/\1/p')
          echo "HYPER_VERSION=$HYPER_VERSION" >> $GITHUB_ENV
      - name: Cache hyperd
        uses: actions/cache@v3
        with:
          path: |
            target/.cache
          key: ${{ runner.os }}-hyper-${{ env.HYPER_VERSION }}
          restore-keys: |
            ${{ runner.os }}-hyper-${{ env.HYPER_VERSION }}
      - name: Maven package
        run: mvn $MAVEN_ARGS clean package --file pom.xml
